[package]
name = "challenges"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.0.0"

[dependencies.serialize]
path = "../serialize"

[dependencies.xor]
path = "../xor"

[dependencies.crypto]
path = "../crypto"